"""
Iteration 2 - Database Setup Script for ShopFlow

Run with:
    PG_DSN=postgresql://postgres:postgres@localhost:5432/shopflow python scripts/db_setup.py
"""

import os
import psycopg

PG_DSN = os.getenv("PG_DSN", "postgresql://postgres:postgres@localhost:5432/shopflow")

DDL = [
    # --- schema ---
    "CREATE SCHEMA IF NOT EXISTS core;",

    # --- dimensions ---
    """
    CREATE TABLE IF NOT EXISTS core.customers (
        id                INT PRIMARY KEY,
        name              TEXT NOT NULL,
        email             TEXT NOT NULL,
        registration_date DATE,
        country           TEXT
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS core.suppliers (
        supplier_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name        TEXT NOT NULL UNIQUE
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS core.categories (
        category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name        TEXT NOT NULL UNIQUE
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS core.payment_methods (
        payment_method_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name              TEXT NOT NULL UNIQUE
    );
    """,

    # --- products (FKs to categories & suppliers) ---
    """
    CREATE TABLE IF NOT EXISTS core.products (
        id          INT PRIMARY KEY,
        name        TEXT NOT NULL,
        category_id INT NOT NULL REFERENCES core.categories(category_id),
        price       NUMERIC(12,2) NOT NULL CHECK (price > 0),
        supplier_id INT NOT NULL REFERENCES core.suppliers(supplier_id)
    );
    """,

    # --- transactions (FKs to customers, products, payment_methods) ---
    """
    CREATE TABLE IF NOT EXISTS core.transactions (
        id                INT PRIMARY KEY,
        customer_id       INT NOT NULL REFERENCES core.customers(id),
        product_id        INT NOT NULL REFERENCES core.products(id),
        quantity          INT NOT NULL CHECK (quantity > 0),
        timestamp         TIMESTAMPTZ NOT NULL,
        payment_method_id INT NOT NULL REFERENCES core.payment_methods(payment_method_id)
    );
    """
]


def main():
    with psycopg.connect(PG_DSN) as conn:
        with conn.cursor() as cur:
            for stmt in DDL:
                cur.execute(stmt)
            conn.commit()
    print("Fist setup done. Schema core created.")
    
    
if  __name__ == "__main__":
    main()